name: win
description: A Dart win library.
version: 0.0.0
homepage: none
repository: none
issue_tracker: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32: ^2.2.9
  meta: ^1.3.0
  path:

dev_dependencies:
  lints: ^1.0.1

