include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    non_constant_identifier_names: false
    prefer_function_declarations_over_variables: false

